### ISSUE TITLE
Lower-cased trello links don't work

### ISSUE THREAD

**Issue by Nyrio** [laramies/theHarvester#143]
Hi,

I have used the tool to find some public Trello boards and files and succeeded to do so. The links are in lower-case though, so in order to find the real URL I have to use my search engine, and even though I quickly find some of the boards, some are harder to reach.

Would it be possible to have the links in the original case?

**Comment by NotoriousRebel** [comment]
Yes, the reason why it was happening is because the trello_urls were getting filtered. When a list gets filtered it creates a new list with everything lowercase.

**Comment by Nyrio** [comment]
Is there any reason to use `lower()` here?:
```python
def filter(lst):
    """
    Method that filters list
    :param lst: list to be filtered
    :return: new filtered list
    """
    lst = set(lst)  # remove duplicates
    new_lst = []
    for item in lst:
        if (item[0].isalpha() or item[0].isdigit()) and ('xxx' not in item) and ('..' not in item):
                new_lst.append(item.lower())
    return new_lst
```

It seems a bit weird to me: this code doesn't prevent having a duplicate in `new_lst` if multiple items were similar but in a different case, and it loses the case information (which can breaks URLs).

**Comment by leebaird** [comment]
URLs are fixed with PR 144.

**Comment by NotoriousRebel** [comment]
Things are lowered for hostnames and emails, Trello urls were mistakingly getting filtered.

**Comment by Nyrio** [comment]
Ok I'm happy with PR #144 then. Closing

**Comment by deathalliance** [comment]
This issue still exists. I'm on theHarvester 3.2.2 and trello links are still being lowercased.
Changing `new_lst.append(item.lower())` to `new_lst.append(item)` solves the issue. I hope this change becomes a permanent part of the code.
