### ISSUE TITLE
Twitter output still doesnt work correctly

### ISSUE THREAD

**Issue by whoot** [laramies/theHarvester#244]
Hey,

the twitter output problem (see #89 and #184 ) is still not fixed!
Getting still the following false positive output:
```
[*] Searching Twitter. 
	Searching 100 results.
	Searching 200 results.
	Searching 300 results.
	Searching 400 results.
	Searching 500 results.

[*] Users found: 9
---------------------
@.1557326674158790
@.1557326682783952
@.1557326689257165
@.1557326698049818
@.1557326705109515
@broofa.com
@keyframes
@media
@webkit-keyframes

[*] No IPs found.

[*] No emails found.

[*] No hosts found.
```

**Comment by jzold** [comment]
Hi,

I'll provide a fix for this one shortly

J./

**Comment by jzold** [comment]
using regex now it filters the following usernames:

[*] Users found: 8
---------------------
@WesleydeSouza
@broofa
@font
@fuckHMSLF
@jonosmoove
@karlwho3
@keyframes
@media

J./

**Comment by broofa** [comment]
@jzold FYI, this sent notifications to all the `@{username}`'s you mentioned.  If you put that output in a code block, it'll avoid annoying people.  Thanks.

**Comment by L1ghtn1ng** [comment]
@broofa I have merged in the fix, can you try again please?

**Comment by broofa** [comment]
@L1ghtn1ng I think you meant to direct that at @jzold.

*/me tries yet again to unsubscribe from this issue. ;-)*

**Comment by L1ghtn1ng** [comment]
Whoops my bad was meant to send that to whoot
________________________________

**Comment by whoot** [comment]
The first time I used it, I was still getting the following output:

```
[*] Searching Twitter usernames using Google. 
	Searching 100 results.
	Searching 200 results.
	Searching 300 results.
	Searching 400 results.
	Searching 500 results.

[*] Users found: 3
---------------------
@broofa
@keyframes
@media

[*] No IPs found.

[*] No emails found.

[*] No hosts found.
```

After that, it worked one more time (same results) and then I always get no results:
```
[*] Searching Twitter usernames using Google. 
	Searching 100 results.
	Searching 200 results.
	Searching 300 results.
	Searching 400 results.
	Searching 500 results.

[*] No users found.



[*] No IPs found.

[*] No emails found.

[*] No hosts found.
```

Maybe google is restricting requests?

**Comment by jzold** [comment]
@whoot yes google doesn't like bot-like searches run against it. This module really needs a bit of thinking and approach sprinkled with twitter API integration. One temp. circumvention is to use a proxy service but that will only get you 1/2 search queries at most...the fix I've added strips out potential CSS related items

J./

**Comment by L1ghtn1ng** [comment]
Going to close this as there are a few modules that use google and need retweaking to get around the issue, will create its own issue for this
