### ISSUE TITLE
Google is blocking your ip and the workaround

### ISSUE THREAD

**Issue by tolgagundogdu** [laramies/theHarvester#362]
Hi;

I got an error:
Google is blocking your ip and the workaround, returning
        Searching 100 results.
Google is blocking your ip and the workaround, returning
        Searching 200 results.
Google is blocking your ip and the workaround, returning
        Searching 300 results.
Google is blocking your ip and the workaround, returning
        Searching 400 results.
Google is blocking your ip and the workaround, returning
        Searching 500 results.

[*] No links found.

**Comment by NotoriousRebel** [comment]
@tolgagundogdu This is a current issue we are dealing with and are working on implementing new workarounds eventually! Are you using the most recent version of the tool? If Google is blocking your ip and the workaround it should exit that block of code and move to the next search engine.

**Comment by tolgagundogdu** [comment]
Yes it jumps to next source but there is no result at the end. I think The Google is the blocking the the biggest part of the investigation.

**Comment by lookaj** [comment]
same issue here :(

**Comment by NotoriousRebel** [comment]
This will be worked on very soon!

**Comment by L1ghtn1ng** [comment]
@NotoriousRebel Think we can close this out as wont this be resolved when #383 is merged?

**Comment by L1ghtn1ng** [comment]
I am closing this as I have just merged #383 which now has proxy support

**Comment by Rlfs023** [comment]
I still have this problem did anyone manage to solve?

**Comment by L1ghtn1ng** [comment]
No it is not possible to our knowledge, the only thing I can think of is route your requests through tor

**Comment by xstfahim-sk** [comment]
Can anyone solve the problem, i tried using proxychains but still it wont works.

**Comment by berkayuuc** [comment]
This problem still maintains. Did any solution to this issue?

**Comment by dogukankurnaz** [comment]
is it resolved?

**Comment by L1ghtn1ng** [comment]
No, this is not something we can fix, there might be a way as there is a tool that has gotten around it but if that technique has already been blocked by Google then no and the only thing that can be done is add socks proxy support
________________________________

**Comment by NextKool** [comment]
We are already 2022 and we still have that problem. Has someone fixed the error?

**Comment by dogukankurnaz** [comment]
No, the problem is not solved yet.

**Comment by AA4111** [comment]
just got google is blocking your ip and the workaround returning error so what should i do to unblock my ip address,
 any sol?

**Comment by L1ghtn1ng** [comment]
You have to wait a day or try using a proxy/vpn

On 11 Jan 2022, at 14:20, Ahmad Ali ***@***.***> wrote:

﻿

just got google is blocking your ip and the workaround returning error so what should i do to unblock my ip address,
any sol?

**Comment by NotoriousRebel** [comment]
As an alternative that should solve the problem; however, will highly likely not be officially supported. You could add some subprocess calls whenever the [AsyncFetecher class is initialized](https://github.com/laramies/theHarvester/blob/master/theHarvester/lib/core.py#L233). Or whenever X amount of requests are made or when you are starting to get blocked by google that talks to a vpn cli for example using the [mullvad cli](https://mullvad.net/en/help/how-use-mullvad-cli/) as an example you could do a subprocess call to `mullvad relay set location se mma se-mma-001` and cycle through different regions. This is just an example if the current solutions are not working, theHarvester will probably not officially support these workarounds as they would not be easy to mantain or scale but for an individual use case this could work.

**Comment by zackariyakrh** [comment]
well you could try to restart your router

**Comment by lekosbelas** [comment]
> Yes it jumps to next source but there is no result at the end. I think The Google is the blocking the the biggest part of the investigation.

Sorunu cozdun mu? 
TR email database in var mi??
Saygilar

**Comment by lekosbelas** [comment]
> No, the problem is not solved yet.

TR email databasein var mi? 
Sorun belliki cozulmemis. Alternatif var mi?

**Comment by Alaponuke** [comment]
Problems still happen
![2022-07-14_12-56-13](https://user-images.githubusercontent.com/92026112/178967429-80f36bfa-f8f0-4329-b73e-3ce21c209313.png)

**Comment by themusicdad** [comment]
myr

**Comment by sidharthmrao** [comment]
Lmao I set a reminder for a year and came back and it's still not solved 😢 so sad.

**Comment by ivanvalcb** [comment]
same here, i tried torctl in order to change my pub ip 
https://www.wikihow.com/Route-All-Network-Traffic-Through-the-Tor-Network#:~:text=The%20Tor%20Network%20is%20a,traffic%20through%20the%20Tor%20Network.

**Comment by L1ghtn1ng** [comment]
In the new release Google has been removed

On 18 Aug 2022, at 18:35, TheUnknownMystery ***@***.***> wrote:

﻿

any solution getting the sam error
